### ISSUE TITLE
We need an input text for story description like pointingpoker did

### ISSUE THREAD

**Issue by just4fun** [IFS49F/poker#31]
![story_description](https://user-images.githubusercontent.com/7512625/28410884-aad303de-6d71-11e7-8889-147038687116.png)

Then every players know which story is being groomed.

**Comment by hyjk2000** [comment]
I gave a thought at this. This is not a difficult feature to implement, but that'll be another responsibility for the moderator and, moreover, one should know which story is being voted unless being inattentive.

**Comment by just4fun** [comment]
I'd like to close this issue since there is no moderator role in current implementation, that said if we create the feature, everyone can update the description, which seems like not a good enhancement.
