### ISSUE TITLE
Emoji can not be displayed on Windows

### ISSUE THREAD

**Issue by just4fun** [IFS49F/poker#32]

**Comment by hyjk2000** [comment]
Correction on issue description: it seems Chrome for Windows and Edge cannot display [Unicode 8.0 emojis](https://emojipedia.org/unicode-8.0/) properly while Firefox works flawlessly. The emoji in question is 🤔  (Thinking Face) which is added in Unicode 8.0.

Cross platform consistency is a problem for emojis. However, I don't feel it's worth the trouble of introducing font or SVG icons. We can choose other emojis from Unicode 6.0 / 6.1, just use Emojipedia to check platform compatibility.
