### ISSUE TITLE
Add friendly warning/banner to user once there is new update for client

### ISSUE THREAD

**Issue by just4fun** [IFS49F/poker#56]
Basically there is no need to use service worker to serve assets since the poker is a simple project.

However, as a side project which is just for fun, I'm happy to embrace such new things.

Thanks to [create-react-app](https://github.com/facebook/create-react-app), there is [registerServiceWorker.js](https://github.com/IFS49F/poker/blob/master/src/registerServiceWorker.js), and it's [easy to know](https://github.com/IFS49F/poker/blob/master/src/registerServiceWorker.js#L22-L33) whether there is new update.

Once there is any change to data structure, I'd like to notice client user there is new update in addition to ensure our code is backward compatible like https://github.com/IFS49F/poker-server/commit/60347c22e356c60bc1985e3778446cf4c0dd6e75.

**Comment by hyjk2000** [comment]
Poker4Fun is a [PWA](https://developers.google.com/web/progressive-web-apps/). The motivation of using Service Worker in Poker4Fun is bringing native-like experience, which is the point of PWA. We want the app launch instantly without having to wait for the assets being downloaded. This is also vital for coping with the screwed up Internet connection in China.

If we are making a native app, I bet you'll agree that it's totally normal for the user to run an old version of the app. As we are building a PWA, we should think in the same way as native app developers. IMO, forcing the user to upgrade immediately is too intrusive for our UX standard, so we don't want to do that even if a breaking change is made on the server.

API versioning is much better way to deal with this problem. We progressively enhance the experience for new version users while keeping the access to old version until they're ready to upgrade.

**Comment by just4fun** [comment]
> If we are making a native app, I bet you'll agree that it's totally normal for the user to run an old version of the app.

Yes I agree.

If we have API change or data structure change, we should make sure it's backward compatibility, then there is no need to ask them to upgrade manually.
