### ISSUE TITLE
Private use in company

### ISSUE THREAD

**Issue by just4fun** [IFS49F/poker#60]
The poker has been released last year. As far as I know, there are at least 3 teams in Active were using it.

As you know the poker is not stable sometimes, because the server is located out of China, so during last weeks, some managers asked me whether we could move the poker back to company. In this way I have no need to pay for the server and domain.

According to the [license](https://github.com/IFS49F/poker/blob/master/LICENSE) of poker, it's OK to fork it to other place, but to be honest, this is just side project which I can introduce any new tech stuff if I like, that said if one of our duties is to maintain the internal poker, seems like there is no fun.

I told the managers that feel free to fork the repo, but we will still maintain the one on GitHub. I'm also happy to be the sponsor for the server and domain, it's not big deal.

@hiveer - As project initiator
@hyjk2000 - As main maintainer
me - As sponsor

Just want to on the same page with you all.

**Comment by hiveer** [comment]
I think we are on the same page for the using of this project. This is an open source project which belongs to the community not any company. We welcome anyone to use it within the authorization of the license.

**Comment by just4fun** [comment]
Thanks guys. I love you all.
