### ISSUE TITLE
Display who clicks `Show` or `Hide`

### ISSUE THREAD

**Issue by just4fun** [IFS49F/poker#61]
Now every player can show or hide the result, we didn't distinguish scrum owner and regular players according to our initial engineering.

However, sometimes the new users want to try it out, which will show the unfinished voting and block our normal process.

Actually we recorded every action for users in our server logs, but our users want to display who show or hide the result in the UI at least.

**Comment by hyjk2000** [comment]
Yes, there are no user roles or access control in Poker4Fun, and it's was designed this way intentionally based on our understanding of grooming sessions, which includes the assumption that everyone participates cooperatively, and does not rely on Poker4Fun for communication.

I agree with your idea. Showing who just clicked _Show_ or _Clear_ is as useful as showing who just voted, for which the necessary data structure has [already](https://github.com/IFS49F/poker/blob/b33b3bbac832e6eb8f05811203fb7e5a4404d5ee/src/pages/Room/Room.js#L80) [been](https://github.com/IFS49F/poker-server/blob/60347c22e356c60bc1985e3778446cf4c0dd6e75/app/socket/index.js#L96) [implemented](https://github.com/IFS49F/poker-server/blob/60347c22e356c60bc1985e3778446cf4c0dd6e75/app/socket/index.js#L117). All we need to do is adding additional action types and UI effect to display them.

**Comment by just4fun** [comment]
![tenor-193586768](https://user-images.githubusercontent.com/7512625/39177527-200da884-47e2-11e8-86f8-c2cf70809c35.gif)
