### ISSUE TITLE
It can change vote even in `show` state

### ISSUE THREAD

**Issue by crusoexia** [IFS49F/poker#65]
When the organizer show the decks, voters still can change votes, which should be prevent. Someone might change his vote during discussion.

**Comment by just4fun** [comment]
The behavior is expected as @hiveer mentioned.

Say all of us are in a grooming meeting, when the result is displayed, both you and hiveer voted 5, but I voted 13, then the organizer will ask why I voted 13. During my explanation, if one of you think 'oh I missed something, so 13 is ok', you may change your point. If not, organizer will also ask us, 'Anyone of you want to change your point?', to make sure everyone is on the same page.

BTW, to indicate anyone who re-votes, we make the bounce animation re-triggered, I think it's enough to show who changes his/her thought when the result is shown.

**Comment by crusoexia** [comment]
@hyjk2000 you are right. For our team we have about 15 persons, it's hard to spot someone has changed his point, and we want explanation for any unnormal points. After the explanations we prefer clear the votes and vote again. But anyway, this still is a handy tool.
